// src/App.jsx
import { useState, useRef } from "react";
import { saveAs } from "file-saver";
import JSZip from "jszip";
import {
  Wand2, Download, RefreshCw, Eye, Code2, Loader2,
  Sparkles, Palette, Layout, Check
} from "lucide-react";
import "./App.css";

const API_BASE = "https://ai-website-generator-6ap6.onrender.com";

const STYLE_OPTIONS = [
  { id: "modern", label: "Modern & Clean" },
  { id: "bold", label: "Bold & Vibrant" },
  { id: "minimal", label: "Minimalist" },
  { id: "luxury", label: "Luxury & Elegant" },
  { id: "playful", label: "Playful & Fun" },
  { id: "corporate", label: "Corporate & Professional" },
];

const COLOR_OPTIONS = [
  { id: "blue", label: "Ocean Blue", color: "#2563eb" },
  { id: "purple", label: "Royal Purple", color: "#7c3aed" },
  { id: "green", label: "Forest Green", color: "#059669" },
  { id: "orange", label: "Sunset Orange", color: "#ea580c" },
  { id: "rose", label: "Rose Pink", color: "#e11d48" },
  { id: "dark", label: "Dark Mode", color: "#1e293b" },
];

const EXAMPLE_PROMPTS = [
  "Portfolio website for a freelance photographer specializing in travel photography",
  "E-commerce site for a handmade jewelry brand called 'Lunar Crafts'",
  "Restaurant landing page for an Italian fine dining restaurant called 'La Bella'",
  "SaaS landing page for a project management tool called 'FlowDesk'",
  "Personal blog for a software developer who writes about AI and productivity",
  "Agency website for a creative digital marketing company called 'Spark Studio'",
];

export default function App() {
  const [prompt, setPrompt] = useState("");
  const [style, setStyle] = useState("modern");
  const [colorScheme, setColorScheme] = useState("blue");
  const [isGenerating, setIsGenerating] = useState(false);
  const [website, setWebsite] = useState(null);
  const [activeTab, setActiveTab] = useState("preview");
  const [refinement, setRefinement] = useState("");
  const [isRefining, setIsRefining] = useState(false);
  const [history, setHistory] = useState([]);
  const [error, setError] = useState(null);
  const iframeRef = useRef(null);

  const handleGenerate = async () => {
    if (!prompt.trim()) return;
    setIsGenerating(true);
    setError(null);
    setWebsite(null);

    try {
      const res = await fetch(`${API_BASE}/api/generate`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ prompt, style, colorScheme }),
      });

      const data = await res.json();
      if (!data.success) throw new Error(data.error || "Generation failed");

      setWebsite(data.website);
      setHistory((prev) => [{ prompt, website: data.website, ts: Date.now() }, ...prev.slice(0, 4)]);
      setActiveTab("preview");
    } catch (err) {
      setError(err.message);
    } finally {
      setIsGenerating(false);
    }
  };

  const handleRefine = async () => {
    if (!refinement.trim() || !website) return;
    setIsRefining(true);
    setError(null);

    try {
      const res = await fetch(`${API_BASE}/api/refine`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          originalPrompt: prompt,
          refinement,
          currentCode: website,
        }),
      });

      const data = await res.json();
      if (!data.success) throw new Error(data.error || "Refinement failed");

      setWebsite(data.website);
      setRefinement("");
      setActiveTab("preview");
    } catch (err) {
      setError(err.message);
    } finally {
      setIsRefining(false);
    }
  };

  const handleDownload = async () => {
    if (!website) return;

    const zip = new JSZip();
    zip.file("index.html", website.fullHtml || `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${website.title}</title>
  <style>${website.css}</style>
</head>
<body>
${website.html}
<script>${website.js}</script>
</body>
</html>`);
    zip.file("styles.css", website.css);
    zip.file("script.js", website.js || "");
    zip.file("README.md", `# ${website.title}\n\n${website.description}\n\nGenerated by AI Website Generator\n\n## Components Used\n${(website.components || []).map((c) => `- ${c}`).join("\n")}`);

    const blob = await zip.generateAsync({ type: "blob" });
    saveAs(blob, `${website.title?.replace(/\s+/g, "-").toLowerCase() || "website"}.zip`);
  };

  return (
    <div className="app">
      <header className="header">
        <div className="header-inner">
          <div className="logo">
            <Wand2 size={22} />
            <span>SiteForge <em>AI</em></span>
          </div>
          <div className="header-badge">Powered by Groq</div>
        </div>
      </header>

      <main className="main">
        <aside className="panel panel-left">
          <div className="panel-section">
            <label className="label">Describe your website</label>
            <textarea
              className="textarea"
              placeholder="e.g. Portfolio website for a freelance photographer..."
              value={prompt}
              onChange={(e) => setPrompt(e.target.value)}
              rows={5}
            />
            <div className="examples">
              <span className="examples-label">Try an example:</span>
              <div className="examples-list">
                {EXAMPLE_PROMPTS.slice(0, 3).map((ex, i) => (
                  <button key={i} className="example-chip" onClick={() => setPrompt(ex)}>
                    {ex.slice(0, 48)}…
                  </button>
                ))}
              </div>
            </div>
          </div>

          <div className="panel-section">
            <label className="label">
              <Layout size={14} /> Design Style
            </label>
            <div className="options-grid">
              {STYLE_OPTIONS.map((s) => (
                <button
                  key={s.id}
                  className={`option-btn ${style === s.id ? "active" : ""}`}
                  onClick={() => setStyle(s.id)}
                >
                  {style === s.id && <Check size={12} />}
                  {s.label}
                </button>
              ))}
            </div>
          </div>

          <div className="panel-section">
            <label className="label">
              <Palette size={14} /> Color Scheme
            </label>
            <div className="color-grid">
              {COLOR_OPTIONS.map((c) => (
                <button
                  key={c.id}
                  className={`color-btn ${colorScheme === c.id ? "active" : ""}`}
                  onClick={() => setColorScheme(c.id)}
                  title={c.label}
                >
                  <span className="color-swatch" style={{ background: c.color }} />
                  <span>{c.label}</span>
                  {colorScheme === c.id && <Check size={11} />}
                </button>
              ))}
            </div>
          </div>

          <button
            className="btn-generate"
            onClick={handleGenerate}
            disabled={isGenerating || !prompt.trim()}
          >
            {isGenerating ? (
              <><Loader2 size={18} className="spin" /> Generating…</>
            ) : (
              <><Sparkles size={18} /> Generate Website</>
            )}
          </button>

          {error && (
            <div className="error-box">
              <strong>Error:</strong> {error}
            </div>
          )}

          {website && (
            <div className="panel-section refine-section">
              <label className="label">Refine your website</label>
              <textarea
                className="textarea"
                placeholder="e.g. Make the hero background dark, add a testimonials section..."
                value={refinement}
                onChange={(e) => setRefinement(e.target.value)}
                rows={3}
              />
              <button
                className="btn-refine"
                onClick={handleRefine}
                disabled={isRefining || !refinement.trim()}
              >
                {isRefining ? (
                  <><Loader2 size={15} className="spin" /> Refining…</>
                ) : (
                  <><RefreshCw size={15} /> Apply Refinement</>
                )}
              </button>
            </div>
          )}
        </aside>

        <section className="panel panel-right">
          {!website && !isGenerating && (
            <div className="empty-state">
              <div className="empty-icon"><Wand2 size={48} /></div>
              <h2>Your website will appear here</h2>
              <p>Describe what you want to build and click <strong>Generate Website</strong></p>
            </div>
          )}

          {isGenerating && (
            <div className="loading-state">
              <div className="loading-orb" />
              <h2>Crafting your website…</h2>
              <p>Claude is generating layout, content, and styles</p>
              <div className="loading-steps">
                {["Processing prompt", "Designing layout", "Writing content", "Styling components"].map((step, i) => (
                  <div key={i} className="loading-step" style={{ animationDelay: `${i * 0.4}s` }}>
                    <Loader2 size={13} className="spin" /> {step}
                  </div>
                ))}
              </div>
            </div>
          )}

          {website && (
            <div className="result-panel">
              <div className="result-header">
                <div className="result-info">
                  <h3>{website.title}</h3>
                  <p>{website.description}</p>
                </div>
                <div className="result-actions">
                  <button className="btn-icon" onClick={() => setActiveTab("preview")} data-active={activeTab === "preview"}>
                    <Eye size={15} /> Preview
                  </button>
                  <button className="btn-icon" onClick={() => setActiveTab("code")} data-active={activeTab === "code"}>
                    <Code2 size={15} /> Code
                  </button>
                  <button className="btn-download" onClick={handleDownload}>
                    <Download size={15} /> Download ZIP
                  </button>
                </div>
              </div>

              {activeTab === "preview" && (
                <div className="preview-container">
                  <iframe
                    ref={iframeRef}
                    title="Generated Website"
                    srcDoc={website.fullHtml}
                    className="preview-iframe"
                    sandbox="allow-scripts allow-same-origin"
                  />
                </div>
              )}

              {activeTab === "code" && (
                <div className="code-tabs">
                  <div className="code-block">
                    <div className="code-label">index.html</div>
                    <pre><code>{website.fullHtml}</code></pre>
                  </div>
                </div>
              )}

              {website.components?.length > 0 && (
                <div className="components-bar">
                  <span>Components:</span>
                  {website.components.map((c, i) => (
                    <span key={i} className="component-tag">{c}</span>
                  ))}
                </div>
              )}
            </div>
          )}
        </section>
      </main>
    </div>
  );
}
